/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Thu Jan 23 14:03:42 KST 2014
    Created by chero@pantech.com (LS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

/*
Current MODEL ID is T_EF59L 
LINUX Kernel Define is as follows
#define CONFIG_MACH_MSM8974_EF59L
*/

#define PT10  0X0010
#define PT20  0X0020
#define WS10  0X0030
#define WS20  0X0040
#define TP10  0X0050
#define TP20  0X0060
#define PP10  0X0070

#define BOARD_VER   TP20

#endif /*BOARD_REV_H*/
