#
# Makefile for nfc devices
#

obj-$(CONFIG_CXD2235AGG_NFC_FELICA) += felica_master.o felica_cen.o felica_pon.o \
								felica_int.o felica_rfs.o felica_rws.o \
								snfc_uart_avail.o snfc_hsel.o snfc_intu.o felica_uart.o snfc_pwr.o snfc_smem.o
obj-$(CONFIG_S7760A) +=s7760a.o								
obj-$(CONFIG_AK6921AF) +=ak6921af.o
